### ISSUE TITLE
Version mismatch in Aspire.MongoDB.Driver

### ISSUE THREAD

**Issue by hades200082** [dotnet/aspire#5427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have `Aspire.MongoDB.Driver` and am using it as follows in my API project:

```cs
builder.AddMongoDBClient("Database");
```

After updating from `Aspire.MongoDB.Driver` 8.0.2 to 8.1.0 I now get an error:

```
Error CS0012 : The type 'MongoClientSettings' is defined in an assembly that is not referenced. You must add a reference to assembly 'MongoDB.Driver, Version=2.27.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by davidfowl** [comment]
cc @eerhardt @sebastienros

**Comment by eerhardt** [comment]
This is a known issue in the MongoDB ecosystem. Between v2.27 and v2.28 they started strong name signing MongoDB.Driver. So now every reference in an app either needs to:

* stay on 2.27 (or earlier)
-or-
* update to 2.28 (or later)

The issue with Aspire is that we also reference https://www.nuget.org/packages/AspNetCore.HealthChecks.MongoDb, which is still on 2.27. So we can't update to 2.28 until it does. We need a new release of that package with https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2265 fixed.

@hades200082 - is it possible for you to downgrade your app to MongoDB.Driver v2.27 until this can be resolved?

**Comment by hades200082** [comment]
@eerhardt That sounds like a right mess.

>  is it possible for you to downgrade your app to MongoDB.Driver v2.27 until this can be resolved?

No, because `MongoDB.EntityFrameworkCore` has `MongoDB.Driver ≥ 2.28.0` in its dependencies.

**Comment by eerhardt** [comment]
> That sounds like a right mess.

Yep - it is. Adding a strong name to an assembly is a breaking change.

> No, because MongoDB.EntityFrameworkCore 8.1.0 has MongoDB.Driver ≥ 2.28.0 in its dependencies.

Can you downgrade to 8.0.3, if you need to get unblocked?

**Comment by hades200082** [comment]
@eerhardt 

> Can you downgrade to 8.0.3, if you need to get unblocked?

Yep. That's what I've done for now. If Mongo are going to be doing this it sounds like the different teams at Microsoft need to collaborate on what versions they reference and when.
